server:
  port: 8001


spring:
  application:
    name:  cloud-provider-hystrix-payment   #项目的名称


eureka:
  client:
    #表示是否将自己注册进 EurekaServer 默认True
    register-with-eureka: true
    # 是否从 EurekaServer 中抓取已有的注册信息，默认true，单节点无所谓，集群必须设置为true，才能配合 ribbon 使用负载均衡
    fetch-registry: true
    service-url:
      # 单机版的配置
      #defaultZone: http://localhost:7001/eureka
      # 集群版的配置
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/

  instance:
    ## 修改主机名称
    instance-id: paymentHystrix8001
    prefer-ip-address: true