server:
  port: 80
spring:
  application:
    name: cloud-order-service   #项目的名称
  # 配置 zipkin  配置监控的结构显示在 zipkin 的页面上
  zipkin:
    base-url: http://localhost:9411
    # 设置采样率介质值，0~1之间  1 表示全部采样
  sleuth:
    sampler:
      probability: 1
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: '000000'
    driver-class-name: com.mysql.cj.jdbc.Driver   #MySQL 驱动包
    type: com.alibaba.druid.pool.DruidDataSource   #当前数据源的操作类型

eureka:
  client:
    # 是否从 EurekaServer 抓取已有的注册信息，默认是true ，单节点无所谓，集群必须设置为true，才能配合 ribbon 使用负载均衡
    fetch-registry: true
    # 表示是否将自己注册进 EurekaServer ，默认是true
    register-with-eureka: true

    service-url:
      # 单机版的配置
      #defaultZone: http://localhost:7001/eureka
      # 集群版的配置
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
  instance:
    instance-id: order80
    prefer-ip-address: true
