server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
    register-with-eureka: false
    ## 开启 feign 支持 Hystrix
feign:
  hystrix:
    enabled: true