server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
    register-with-eureka: false

logging:
  level:
    ## feign 日志以什么级别监控那个接口
    ## 以 debug 打印 full 级别的日志
    com.zhi.springcloud.service.PaymentFeignService: debug
