server:
  port: 9527
spring:
  application:
    name: cloud-gateway
    ## 配置网关
  cloud:
    gateway:
      # 开启从注册中心动态创建路由的功能，利用微服务名进行路由，将下面配置的 写死uri 进行注释掉，使用动态配置的uri
      discovery:
        locator:
          enabled: true
      routes:
        ## routes 表示下面的配置可以配置多套，，下面进行演示，配置两套
        ##  路由的ID，没有固定规则，但是要求ID必须唯一
        - id: payment_routh
        ## 路由匹配成功后，提供服务器的路由地址，这里的uri 是写死的，应该采用动态路由配置
        ##uri: http://localhost:8001
          uri: lb://cloud-payment-service #  匹配后提供服务的路由地址
        ## 断言，路径相匹配的进行路由
          predicates:
            - Path=/payment/get/**

        ##  路由的ID，没有固定规则，但是要求ID必须唯一
        - id: payment_routh2
          ## 路由匹配成功后，提供服务器的路由地址 这里的uri 是写死的，应该采用动态路由配置
          ##uri: http://localhost:8001
          uri: lb://cloud-payment-service #  匹配后提供服务的路由地址
          ## 断言，路径相匹配的进行路由
          predicates:
            - Path=/payment/lb/**

eureka:
  instance:
    hostname: cloud-gateway-service
  client:  ## 网关 注册进Eureka 中
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
