server:
  port: 80
spring:
  application:
    # 服务别名----注册 zookeeper到注册中心的名称
    name: cloud-consumer-order
  cloud:
    zookeeper:
      connect-string: 192.168.74.128:2181   #注册到 zookeeper 的地址和端口号

  datasource:
    url: jdbc:mysql://localhost:3306/cloud?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: '000000'
    driver-class-name: com.mysql.cj.jdbc.Driver   #MySQL 驱动包
    type: com.alibaba.druid.pool.DruidDataSource   #当前数据源的操作类型