server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        # Nacos 服务注册中心的地址
        server-addr: localhost:8848
    sentinel:
      transport:
        #  Sentinel Dashboard 的地址
        dashboard: localhost:8080
        # 默认 8791 端口，假如端口被占用，就从 8791开始扫描，依次加一，直到扫描到未被占用的端口
        port: 8791
        clientIp: localhost
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: "*"