server:
  port: 3344
spring:
  application:
    name: cloud-config-center # 注册进 Eureka 服务中的名称
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JiuQianQiO/mySpringMVC.git  # 在GitHub 上搜索 git 仓库的名称
          ## 搜索目录,也就是仓库的名称
          search-paths:
            - mySpringMVC
      label: config
## 添加 RabbitMQ 的相关支持
## 注意这里一定要顶格写，在客户端3355、3366 是不需要定格写的
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

## RabbitMQ 相关配置，暴露 bus 刷新配置的端点
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
